[project]
name = "pypqc"
version = "0.0.0.8"

[tool.setuptools.packages.find]
include = ["pqc"]
namespaces = false

[tool.setuptools.exclude-package-data]
"pqc" = ["*.c"]

[build-system]
requires = [
    'cffi >= 1.14.5',
    'setuptools >= 49.5.0',
]
