
[project]
name = "pypqc"
version = "0.0.0.1"
dependencies = [
    'asn1',
    'cryptography'
]

[tool.setuptools.packages.find]
include = ["pqc"]
namespaces = false

[tool.setuptools.exclude-package-data]
"pqc" = ["*.c"]

[build-system]
requires = [
    'setuptools',
    'cffi',
]
build-backend = "_build_pep517"
backend-path = ["."]
