name: Build

on: [push]

jobs:
  build_wheels:
    name: bdist_wheel for ${{ matrix.py-impl }} on ${{ matrix.os }}
    runs-on: ${{ matrix.github_os }}
    strategy:
      matrix:
        # FIXME? PQClean GNU extensions break clang thus the default toolchain used by CIBW on Github Actions MacOS
        os: [Windows, Mac, Linux]
        py-impl: ["CPython 3.X", "PyPy 3.X"]
        include:
          - os: Windows
            github_os: windows-2019
          - os: Mac
            github_os: macos-11
          - os: Linux
            github_os: ubuntu-20.04
          - py-impl: "CPython 3.X"
            cibw_build: "cp3*"
          - py-impl: "PyPy 3.X"
            cibw_build: "pp3*"

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.3

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_BUILD_VERBOSITY: 1
          # FIXME? cibuildwheel doesn't property implement delvewheel yet (delvewheel needs Python 3.7+ runtime, but CPython doesn't support using non-current runtimes for REPAIR_WHEEL_COMMAND)
          # FIXME? PQClean GNU extensions break musl
          CIBW_SKIP: "cp36-* *-musllinux_*"
          # https://cibuildwheel.readthedocs.io/en/stable/options/#:~:text=cibuildwheel%20doesn%27t%20yet%20ship%20a%20default%20repair%20command%20for%20Windows%2E
          CIBW_BEFORE_BUILD_WINDOWS: "pip install delvewheel"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -w {dest_dir} {wheel}"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
